Develop
sashajaaa/java-filmorate pull request #20
Opened 2023-04-09 22:04 UTC by sashajaaa

2023-04-10 19:30 UTC, kalitva requested changes

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public final DirectorService directorService;
private

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public void addLike(@PathVariable Integer id, @PathVariable Integer userId) {
`@PathVariable Long id, @PathVariable Long userId`

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        feedService.addFeed(Long.valueOf(userId), EventType.LIKE, OperationType.ADD, Long.valueOf(id));
Многовато параметров, оптимальное количество параметров 1 - 2, 3 уже многовато, больше 3х - плохо, желательно порефакторить. Соответственно метод `FeedService#addFeed` принимает два айдишника, формирует объект ивента и передает этот объект в сторадж

Актуально для других подобных кейсов

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        feedService.addFeed(Long.valueOf(savedReview.getUserId()), EventType.REVIEW,
Необходимо определиться с типом айдишника - либо везде `Long`, либо везде `Integer`. Обычно используется `Long`

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +        if (feed.isEmpty()) {
В данном случае `Optional` задуман не так использоваться. Нужно в `Optional#orElseThrow` передать саплайер (реализация `java.util.function.Supplier`) c исключением

https://www.baeldung.com/java-optional#or-else-throw

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                chooseId = 3;
Пожалуйста, вынесите в константы эти значения фильтров, а лучше используйте для этих целей `enum`

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        for (Integer filmId : userLikes) {
А чего не стрим апи?

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sql_query/ReviewQuery.java
> +	@Value("${review.select-review-by-id}")
Не очень хорошая идея хранить запросы в конфигах, приходится каждый раз лезть в конфиг чтобы прочитать запрос

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        if (isPresentInDB(director)) {
Это необходимо проверять в сервисе, перед вызовом `addDirector`

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        SqlRowSet idRow = getIdRowsFromDB(director);
Пожалуйста, без лишних запросов. Чтобы получить айдишник можно использовать `KeyHolder`

https://www.baeldung.com/spring-jdbc-autogenerated-keys

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        SqlRowSet idsRow = jdbcTemplate.queryForRowSet(requestAllIDs);
Здесь не нужен `SqlRowSet`, необходимо использовать `JdbcTemplate#query`

https://www.baeldung.com/spring-jdbc-autogenerated-keys

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +            directors.add(getDirectorById(id));
Недопустимо в цикле делать обращения к БД, тем более в таком простом запросе как достать список всех объектов

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        SqlRowSet directorRow = getDirectorRowByID(id);
Никаких `SqlRowSet`, чтобы достать один объект необходимо использовать `JdbcTemplate#queryForObject`

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        }
То же, эти проверки должны быть в сервисах

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        } catch (DataIntegrityViolationException | BadSqlGrammarException ex) {
Эти исключения не должны перехватываться. Если они вылетают, значит что-то где-то накосячено

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +        Director updatedDirector = getDirectorById(director.getId());
Пожалуйста, не надо лишних запросов

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +            jdbcTemplate.execute(requestResetPK);
В этом нет необходимости

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +            jdbcTemplate.execute(requestDeleteById + idsRow.getInt("director_id"));
Это делается **одним** запросом

2023-04-10 19:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/DirectorDbStorage.java
> +    private boolean isPresentInDB(Director director) {
`isPresentInDB --> isPresentInDb`

Пожалуйста, код-стайл

https://google.github.io/styleguide/javaguide.html#s5.3-camel-case

Здесь и в остальных методах ниже

2023-04-10 19:52 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/sql_query/ReviewQuery.java
> +	@Value("${review.select-review-by-id}")
как сделать лучше?

2023-04-10 20:36 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                chooseId = 3;
заменено на enum

2023-04-11 13:20 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/sql_query/ReviewQuery.java
> +	@Value("${review.select-review-by-id}")
И не лучшая идея использовать final для данного класса, так как в иделе имплементить класс от интерфейса с методами без приставки get. Но, учитывая, что проект учебный, а для чистоты процесса мы можем каждый раз обратиться в конфигурационный файл, то я оставил это таким образом. Беды в этом ровным счетом никакой, но для решения проблемы я могу использовать Spring Cache с библиотекой SimpleCache, что обеспечит константный доступ к запросам, так как при первом обращении к запросу он просто кеширует его, однако оставит нам подарок в виде динамики. Либо, можно использовать другой класс и написать свой, простой кеш с мапой. В общем, решение проблемы есть, смысла переделывать я не вижу. На работу это не влияет сейчас, тем более в учебном проекте. Все в команде в курсе, что стоит использовать кэширование и какие есть минусы и плюсы у данной реализации.

2023-04-11 13:21 UTC, Saeldrit commented on src/main/java/ru/yandex/practicum/filmorate/sql_query/ReviewQuery.java
> +	@Value("${review.select-review-by-id}")
И не лучшая идея использовать final для данного класса, так как в иделе имплементить класс от интерфейса с методами без приставки get. Но, учитывая, что проект учебный, а для чистоты процесса мы можем каждый раз обратиться в конфигурационный файл, то я оставил это таким образом. Беды в этом ровным счетом никакой, но для решения проблемы я могу использовать Spring Cache с библиотекой SimpleCache, что обеспечит константный доступ к запросам, так как при первом обращении к запросу он просто кеширует его, однако оставит нам подарок в виде динамики. Либо, можно использовать другой класс и написать свой, простой кеш с мапой. В общем, решение проблемы есть, смысла переделывать я не вижу. На работу это не влияет сейчас, тем более в учебном проекте. Все в команде в курсе, что стоит использовать кэширование и какие есть минусы и плюсы у данной реализации.

2023-04-11 17:10 UTC, merged